abstract: Manipulate file metadata
author: Jonathan Rockway <jrockway@cpan.org
build_requires: 
  Directory::Scratch: 0.05
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: Perl
name: File-Attributes
no_index: 
  directory: 
    - inc
    - t
requires: 
  Best: 0.06
  Carp: 0
  Exporter: 0
  File::Spec: 0
  Module::Pluggable: 0
  YAML: 0
version: 0.02
